apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: tickit
build:
  artifacts:
    - image: anmitdev/auth
      context: auth
      docker:
        dockerfile: Dockerfile
    - image: anmitdev/client
      context: client
      docker:
        dockerfile: Dockerfile
    - image: anmitdev/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/ingress-srv.yaml
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/client-depl.yaml
    - infra/k8s/tickets-depl.yaml
    # - infra/k8s/tickets-mongo-depl.yaml

